# Generated by Django 5.2.7 on 2025-11-02 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_extend_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='admin_note',
        ),
        migrations.RemoveField(
            model_name='user',
            name='appraiser_class',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='certificate1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='certificate2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_info',
        ),
        migrations.RemoveField(
            model_name='user',
            name='education',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_opt_in',
        ),
        migrations.RemoveField(
            model_name='user',
            name='english_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='homepage_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='user',
            name='korean_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='message_opt_in',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_primary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_secondary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='resident_registration_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialty_primary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialty_secondary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialty_tertiary',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='superuser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.PositiveSmallIntegerField(default=99),
        ),
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_agreement', models.BooleanField(default=False)),
                ('email_agreement_at', models.DateTimeField(auto_now_add=True)),
                ('message_agreement', models.BooleanField(default=False)),
                ('message_agreement_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMetaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korean_name', models.CharField(blank=True, max_length=50, null=True)),
                ('english_name', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_primary', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_secondary', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/')),
                ('appraiser_class', models.CharField(blank=True, max_length=30, null=True)),
                ('specialty_primary', models.PositiveSmallIntegerField(blank=True, choices=[(1, '건축'), (2, '토목'), (3, '환경'), (4, '전기'), (5, '설비'), (6, '건축,토목구조'), (7, '문화재'), (8, '법률')], null=True)),
                ('specialty_secondary', models.PositiveSmallIntegerField(blank=True, choices=[(1, '건축'), (2, '토목'), (3, '환경'), (4, '전기'), (5, '설비'), (6, '건축,토목구조'), (7, '문화재'), (8, '법률')], null=True)),
                ('specialty_tertiary', models.PositiveSmallIntegerField(blank=True, choices=[(1, '건축'), (2, '토목'), (3, '환경'), (4, '전기'), (5, '설비'), (6, '건축,토목구조'), (7, '문화재'), (8, '법률')], null=True)),
                ('company_info', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('certificate1', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate2', models.CharField(blank=True, max_length=255, null=True)),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
