# Generated by Django 5.2.7 on 2025-11-04 07:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
