# Generated by Django 5.2.7 on 2025-11-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usermetainfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
