# Generated by Django 5.2.7 on 2025-12-07 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_usermetainfo_certificate1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermetainfo',
            name='specialty_tertiary',
        ),
        migrations.AlterField(
            model_name='usercareer',
            name='assigned_task',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usercareer',
            name='company',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usercareer',
            name='position',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='issuer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='license_no',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='degree',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='major',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='school_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='status',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='UserAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('issuer', models.TextField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExternalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('publisher', models.TextField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
