# Generated by Django 5.2.7 on 2025-12-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_usermetainfo_specialty_tertiary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetainfo',
            name='activity_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermetainfo',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermetainfo',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usermetainfo',
            name='company_industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermetainfo',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usermetainfo',
            name='company_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usermetainfo',
            name='company_task',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usermetainfo',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermetainfo',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermetainfo',
            name='specialty_primary',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '건축'), (2, '토목'), (3, '환경'), (4, '전기'), (5, '설비'), (6, '건축구조'), (7, '문화재'), (8, '법률'), (9, '토목구조')], null=True),
        ),
        migrations.AlterField(
            model_name='usermetainfo',
            name='specialty_secondary',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '건축'), (2, '토목'), (3, '환경'), (4, '전기'), (5, '설비'), (6, '건축구조'), (7, '문화재'), (8, '법률'), (9, '토목구조')], null=True),
        ),
    ]
