# Generated by Django 5.2.7 on 2025-12-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_usermetainfo_activity_region_usermetainfo_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetainfo',
            name='activity_region_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermetainfo',
            name='activity_region_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
