# Generated by Django 5.2.7 on 2025-12-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_usermetainfo_activity_region_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragreement',
            name='privacy_policy_250923',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='privacy_policy_250923_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
