# Generated by Django 5.2.7 on 2025-12-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_useragreement_privacy_policy_250923_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
