# Generated by Django 5.2.7 on 2026-01-14 15:42

import dcclone.utils.fs
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_is_deleted_user_is_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetainfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=dcclone.utils.fs.MediaFileSystemStorage(), upload_to=users.models.upload_to_file),
        ),
    ]
