# Generated by Django 5.2.7 on 2026-01-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_usermetainfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetainfo',
            name='specialty_primary',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '건축'), (2, '토목'), (3, '환경'), (4, '전기'), (5, '설비'), (6, '건축구조'), (9, '토목구조'), (7, '문화재'), (8, '법률'), (10, '안전')], null=True),
        ),
        migrations.AlterField(
            model_name='usermetainfo',
            name='specialty_secondary',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '건축'), (2, '토목'), (3, '환경'), (4, '전기'), (5, '설비'), (6, '건축구조'), (9, '토목구조'), (7, '문화재'), (8, '법률'), (10, '안전')], null=True),
        ),
    ]
