# Generated by Django 5.2.7 on 2026-04-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_usermetainfo_specialty_primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
