services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: dcclone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  s3:
    image: rustfs/rustfs:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      RUSTFS_ADDRESS: :9000 
      RUSTFS_SERVER_DOMAINS: example.com 
      RUSTFS_ACCESS_KEY: rustfsadmin 
      RUSTFS_SECRET_KEY: rustfsadmin 
      RUSTFS_CONSOLE_ENABLE: true 
    volumes:
      - s3_storage:/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - media:/app/media
    depends_on:
      - db

volumes:
  pgdata:
  media:
  s3_storage:
