
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: dcclone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - media:/app/media
    depends_on:
      - db
volumes:
  pgdata:
  media:
