# Generated by Django 5.2.7 on 2025-11-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_is_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='permission_per_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gallery',
            name='permission_read',
            field=models.PositiveSmallIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='gallery',
            name='permission_write',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
