# Generated by Django 5.2.7 on 2025-11-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gallery_permission_per_post_gallery_permission_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='allow_comments',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
