# Generated by Django 5.2.7 on 2025-11-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gallery_allow_comments_alter_gallery_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
