# Generated by Django 5.2.7 on 2025-12-11 15:55

import core.models
import dcclone.utils.fs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_external_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=dcclone.utils.fs.MediaFileSystemStorage(), upload_to=core.models.upload_to_file),
        ),
    ]
