# Generated by Django 5.2.7 on 2026-01-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='permission_admin',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
