# Generated by Django 5.2.7 on 2025-10-27 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal title for the ad.', max_length=255)),
                ('image_large', models.ImageField(help_text='The ad image file.', upload_to='ads/%Y/%m/%d/')),
                ('image_small', models.ImageField(help_text='The ad image file.', upload_to='ads/%Y/%m/%d/')),
                ('link_url', models.URLField(blank=True, help_text='URL the ad links to when clicked.', max_length=2048, null=True)),
                ('location', models.CharField(choices=[('hero', 'Hero Section (Slideshow)'), ('sidebar', 'Sidebar Ad'), ('banner', 'Banner Ad'), ('partner', 'Partner Ad')], db_index=True, default='hero', help_text='Where this ad will be displayed.', max_length=50)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the ad starts being visible.')),
                ('end_date', models.DateTimeField(help_text='Date and time when the ad stops being visible.')),
                ('is_active', models.BooleanField(default=True, help_text='Manually toggle this ad on or off.')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order for display. 0 is highest.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['order', '-start_date'],
            },
        ),
    ]
