# Generated by Django 5.2.7 on 2025-11-04 07:31

import ads.models
import ads.utils.fs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image_large',
            field=models.ImageField(help_text='The ad image file.', storage=ads.utils.fs.MediaFileSystemStorage(), upload_to=ads.models.upload_to_image_large),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_small',
            field=models.ImageField(help_text='The ad image file.', storage=ads.utils.fs.MediaFileSystemStorage(), upload_to=ads.models.upload_to_image_large),
        ),
    ]
