# Generated by Django 5.2.7 on 2025-11-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_image_large_alter_ad_image_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='link_url',
            field=models.TextField(blank=True, help_text='URL the ad links to when clicked.', max_length=4096, null=True),
        ),
    ]
