# Generated by Django 5.2.7 on 2025-11-09 05:26

import ads.models
import ads.utils.fs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image_small',
            field=models.ImageField(help_text='The ad image file.', storage=ads.utils.fs.MediaFileSystemStorage(), upload_to=ads.models.upload_to_image_small),
        ),
    ]
