# Generated by Django 5.2.7 on 2025-12-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='level_required',
            field=models.PositiveSmallIntegerField(default=50, help_text='User level must be less than or equal to this value to view.'),
        ),
    ]
