# Generated by Django 5.2.7 on 2026-04-11 07:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_gallery_permission_admin'),
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('gallery', 'author', 'file')},
        ),
    ]
